import { Inter } from 'next/font/google'
import './globals.css'
import { AuthProvider } from '@/app/context/contextAuth'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'BarberiApp | Todas tus peluquerias, en un solo lugar',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: { apple: '/icon.png' },
}

export const viewport = {
  themeColor: '#fff',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <div className="contenedorPrincipal bg-light">
          {/* <Image src="/fondo-login.jpg" width={100} height={100} alt="lemurs" class="bg-image" /> */}
            {children}

            {/* <Install /> */}
          </div>
        </body>
      </AuthProvider>
    </html>
  )
}
